apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhanvi-cars-backend
  namespace: jhanvi-cars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhanvi-cars-backend
  template:
    metadata:
      labels:
        app: jhanvi-cars-backend
    spec:
      containers:
        - name: backend
          image: jhanviadmin/jhanvi-cars-backend:IMAGE_TAG
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
