apiVersion: v1
kind: Service
metadata:
  name: jhanvi-cars-backend
  namespace: jhanvi-cars
spec:
  type: NodePort
  selector:
    app: jhanvi-cars-backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
