name: Jhanvi Cars Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend-recovered/app
          push: true
          tags: |
            jhanviadmin/jhanvi-cars-backend:latest
            jhanviadmin/jhanvi-cars-backend:${{ github.sha }}
jobs:

  build-and-push:
    runs-on: ubuntu-latest

    # your existing CI steps...


  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Verify Kubernetes
        run: |
          kubectl get nodes

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/
